MODEL:
  TYPE: spvit_swin
  NAME: spvit_swin_bs_l01_t100_search
  DROP_PATH_RATE: 0.5
  SWIN:
    EMBED_DIM: 128
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 4, 8, 16, 32 ]
    WINDOW_SIZE: 7
DATA:
  NUM_WORKERS: 10
  BATCH_SIZE: 128
  DATA_PATH: dataset/imagenet
  DATASET: imagenet
EXTRA:
  loss_lambda: 0.1
  arc_decay: 150
  target_flops: 10.0
  arc_warmup: 0
  arc_min_lr: 5e-4
  architecture_lr: 5e-4
  alpha: 1e2
  theta: 1.5
TRAIN:
  EPOCHS: 300
  WARMUP_EPOCHS: 0
  BASE_LR: 5e-5
  MIN_LR: 5e-5
#EVAL_MODE: True